//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string fathername { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public Nullable<int> gender_id { get; set; }
        public Nullable<int> marriage_status_id { get; set; }
        public string image { get; set; }
        public Nullable<int> education_degree_id { get; set; }
        public string education_institution { get; set; }
        public string education_faculty { get; set; }
        public Nullable<int> work_experience_id { get; set; }
        public string work_experience_about { get; set; }
        public Nullable<int> category_id { get; set; }
        public string position { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> minimum_salary { get; set; }
        public string lang_skills { get; set; }
        public string other_skills { get; set; }
        public string addition_information { get; set; }
        public string email { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string address { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual City City { get; set; }
        public virtual Education_degrees Education_degrees { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Marriage_status Marriage_status { get; set; }
        public virtual Work_experience Work_experience { get; set; }
    }
}
