//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobSearchDbEntities : DbContext
    {
        public JobSearchDbEntities()
            : base("name=JobSearchDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Education_degrees> Education_degrees { get; set; }
        public virtual DbSet<Employer> Employers { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Marriage_status> Marriage_status { get; set; }
        public virtual DbSet<Work_experience> Work_experience { get; set; }
    }
}
